***Import Required Libraries***

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("housing_encoding_last.csv")

In [48]:
df['price_class']=pd.qcut(df['price_usd_log'],q=3,labels=[0,1,2])

# classification
X=['house_age','no_rooms','sqm','year','quarter_num','house_type_Summerhouse','house_type_Townhouse','house_type_Villa',
   'region_Jutland','region_Zealand','sales_type_family_sale','sales_type_regular_sale']

X_class=df[X]
y_class=df['price_class']

# split data to train data and test data
X_train,X_test,y_train,y_test=train_test_split(X_class,y_class,test_size=0.3,random_state=42)

# decision tree
model=DecisionTreeClassifier(max_depth=13,min_samples_leaf=20,class_weight='balanced',random_state=42)
model.fit(X_train,y_train)

# predict unseen data
# Test Set
y_pred=model.predict(X_test)

#calculate accuracy for test data
accuracy=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)

print("Accuracy on test data:",accuracy)
print("Confusion Matrix:")
print(" LOW  MID  HIGH")
print(cm)

Accuracy on test data: 0.5994797121524376
Confusion Matrix:
 LOW  MID  HIGH
[[6366 2338 1197]
 [2599 4539 2897]
 [ 874 1950 6839]]


In [49]:
# random forest
model=RandomForestClassifier(n_estimators=300,
    max_depth=25,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1)
model.fit(X_train,y_train)

# predict unseen data
# Test Set
y_pred=model.predict(X_test)

#calculate accuracy for test data
accuracy=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)

print("Accuracy on test data:",accuracy)
print("Confusion Matrix:")
print(" LOW   MID  HIGH")
print(cm)


Accuracy on test data: 0.6197168823271056
Confusion Matrix:
 LOW   MID  HIGH
[[6573 2373  955]
 [2495 5010 2530]
 [ 783 2120 6760]]
